/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import interface_pack.AnimationInterface;
import interface_pack.ValidationInterface;
import java.awt.HeadlessException;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class TelaCadastro extends javax.swing.JFrame implements AnimationInterface, ValidationInterface {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        caracterGreen8.setVisible(false);
        caracterRed8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaCadastro = new javax.swing.JPanel();
        txtCriarContaGreenDark = new javax.swing.JLabel();
        txtCriarContaGreen = new javax.swing.JLabel();
        txtNomeCompletoGreenDark = new javax.swing.JLabel();
        txtNomeCompletoGreen = new javax.swing.JLabel();
        txtEmailGreenDark = new javax.swing.JLabel();
        txtEmailGreen = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        maskInputEmail = new javax.swing.JLabel();
        txtTelefoneGreenDark = new javax.swing.JLabel();
        txtTelefoneGreen = new javax.swing.JLabel();
        inputTelefone = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        txtSenhaGreenDark = new javax.swing.JLabel();
        txtSenhaGreen = new javax.swing.JLabel();
        maskInputSenha = new javax.swing.JLabel();
        btnCadastrarGreenDark = new javax.swing.JLabel();
        btnCadastrarGreen = new javax.swing.JLabel();
        caracterGreen8 = new javax.swing.JLabel();
        caracterRed8 = new javax.swing.JLabel();
        manSpace = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        maskInputNome = new javax.swing.JLabel();
        frameCadastro = new javax.swing.JLabel();
        verificarSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(869, 459));
        setMinimumSize(new java.awt.Dimension(869, 459));
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telaCadastro.setMaximumSize(new java.awt.Dimension(869, 459));
        telaCadastro.setMinimumSize(new java.awt.Dimension(869, 459));
        telaCadastro.setName(""); // NOI18N
        telaCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCriarContaGreenDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Criar Conta.png"))); // NOI18N
        txtCriarContaGreenDark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCriarContaGreenDarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCriarContaGreenDarkMouseExited(evt);
            }
        });
        telaCadastro.add(txtCriarContaGreenDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 57, -1, -1));

        txtCriarContaGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Criar Conta (1).png"))); // NOI18N
        telaCadastro.add(txtCriarContaGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 57, -1, -1));

        txtNomeCompletoGreenDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nome Completo.png"))); // NOI18N
        txtNomeCompletoGreenDark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNomeCompletoGreenDarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNomeCompletoGreenDarkMouseExited(evt);
            }
        });
        telaCadastro.add(txtNomeCompletoGreenDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 122, -1, -1));

        txtNomeCompletoGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nome Completo (1).png"))); // NOI18N
        telaCadastro.add(txtNomeCompletoGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 122, -1, -1));

        txtEmailGreenDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/E-mail.png"))); // NOI18N
        txtEmailGreenDark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEmailGreenDarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEmailGreenDarkMouseExited(evt);
            }
        });
        telaCadastro.add(txtEmailGreenDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 200, -1, -1));

        txtEmailGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/E-mail (1).png"))); // NOI18N
        telaCadastro.add(txtEmailGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 200, -1, -1));

        inputEmail.setBackground(new java.awt.Color(31, 50, 42));
        inputEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(255, 255, 255));
        inputEmail.setBorder(null);
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        telaCadastro.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 224, 200, 28));

        maskInputEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button (1).png"))); // NOI18N
        telaCadastro.add(maskInputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 222, 222, 31));

        txtTelefoneGreenDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Telefone.png"))); // NOI18N
        txtTelefoneGreenDark.setToolTipText("");
        txtTelefoneGreenDark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTelefoneGreenDarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtTelefoneGreenDarkMouseExited(evt);
            }
        });
        telaCadastro.add(txtTelefoneGreenDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 122, -1, -1));

        txtTelefoneGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Telefone (1).png"))); // NOI18N
        txtTelefoneGreen.setToolTipText("");
        telaCadastro.add(txtTelefoneGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 122, -1, -1));

        inputTelefone.setBackground(new java.awt.Color(31, 50, 42));
        inputTelefone.setBorder(null);
        inputTelefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            inputTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputTelefone.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        telaCadastro.add(inputTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 145, 187, 28));

        txtTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button (1).png"))); // NOI18N
        telaCadastro.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 145, -1, -1));

        inputSenha.setBackground(new java.awt.Color(31, 50, 42));
        inputSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inputSenha.setForeground(new java.awt.Color(255, 255, 255));
        inputSenha.setBorder(null);
        inputSenha.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                inputSenhaMouseMoved(evt);
            }
        });
        inputSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputSenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputSenhaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inputSenhaMouseReleased(evt);
            }
        });
        inputSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaActionPerformed(evt);
            }
        });
        inputSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputSenhaKeyPressed(evt);
            }
        });
        telaCadastro.add(inputSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 225, 100, 25));

        txtSenhaGreenDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Senha.png"))); // NOI18N
        txtSenhaGreenDark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSenhaGreenDarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSenhaGreenDarkMouseExited(evt);
            }
        });
        telaCadastro.add(txtSenhaGreenDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 202, 42, 13));

        txtSenhaGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Senha (1).png"))); // NOI18N
        telaCadastro.add(txtSenhaGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 202, 42, 13));

        maskInputSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button (1).png"))); // NOI18N
        maskInputSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maskInputSenhaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maskInputSenhaMousePressed(evt);
            }
        });
        telaCadastro.add(maskInputSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 223, -1, -1));

        btnCadastrarGreenDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 2.png"))); // NOI18N
        btnCadastrarGreenDark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarGreenDarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarGreenDarkMouseExited(evt);
            }
        });
        telaCadastro.add(btnCadastrarGreenDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 319, 141, 31));

        btnCadastrarGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 2 (1).png"))); // NOI18N
        telaCadastro.add(btnCadastrarGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 319, 141, 31));

        caracterGreen8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/validacaoGreenCaracteres8.png"))); // NOI18N
        telaCadastro.add(caracterGreen8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        caracterRed8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/validacaoRedCaracteres8.png"))); // NOI18N
        telaCadastro.add(caracterRed8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        manSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manSpace.png"))); // NOI18N
        telaCadastro.add(manSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        inputNome.setBackground(new java.awt.Color(31, 50, 42));
        inputNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        inputNome.setForeground(new java.awt.Color(255, 255, 255));
        inputNome.setBorder(null);
        telaCadastro.add(inputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 145, 200, 28));

        maskInputNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button (1).png"))); // NOI18N
        telaCadastro.add(maskInputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 145, 222, 31));

        frameCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tela Cadastro.png"))); // NOI18N
        frameCadastro.setMaximumSize(new java.awt.Dimension(869, 459));
        frameCadastro.setMinimumSize(new java.awt.Dimension(869, 459));
        frameCadastro.setPreferredSize(new java.awt.Dimension(869, 459));
        telaCadastro.add(frameCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, -1, 890, 470));
        frameCadastro.getAccessibleContext().setAccessibleName("telaCadastroFrame");

        verificarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verificarSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verificarSenhaMouseExited(evt);
            }
        });
        telaCadastro.add(verificarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 260, 110));

        getContentPane().add(telaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCriarContaGreenDarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCriarContaGreenDarkMouseEntered
        // TODO add your handling code here:
        turnOnAnimation(txtCriarContaGreenDark, txtCriarContaGreen);
    }//GEN-LAST:event_txtCriarContaGreenDarkMouseEntered

    private void txtCriarContaGreenDarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCriarContaGreenDarkMouseExited
        // TODO add your handling code here:
        turnOffAnimation(txtCriarContaGreenDark, txtCriarContaGreen);
    }//GEN-LAST:event_txtCriarContaGreenDarkMouseExited

    private void txtNomeCompletoGreenDarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeCompletoGreenDarkMouseEntered
        // TODO add your handling code here:
        turnOnAnimation(txtNomeCompletoGreenDark, txtNomeCompletoGreen);
    }//GEN-LAST:event_txtNomeCompletoGreenDarkMouseEntered

    private void txtNomeCompletoGreenDarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeCompletoGreenDarkMouseExited
        // TODO add your handling code here:
        turnOffAnimation(txtNomeCompletoGreenDark, txtNomeCompletoGreen);
    }//GEN-LAST:event_txtNomeCompletoGreenDarkMouseExited

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailActionPerformed

    private void txtEmailGreenDarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailGreenDarkMouseEntered
        // TODO add your handling code here:
        turnOnAnimation(txtEmailGreenDark, txtEmailGreen);
    }//GEN-LAST:event_txtEmailGreenDarkMouseEntered

    private void txtEmailGreenDarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailGreenDarkMouseExited
        // TODO add your handling code here:
        turnOffAnimation(txtEmailGreenDark, txtEmailGreen);
    }//GEN-LAST:event_txtEmailGreenDarkMouseExited

    private void txtTelefoneGreenDarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefoneGreenDarkMouseEntered
        // TODO add your handling code here:
        turnOnAnimation(txtTelefoneGreenDark, txtTelefoneGreen);
    }//GEN-LAST:event_txtTelefoneGreenDarkMouseEntered

    private void txtTelefoneGreenDarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefoneGreenDarkMouseExited
        // TODO add your handling code here:
        turnOffAnimation(txtTelefoneGreenDark, txtTelefoneGreen);
    }//GEN-LAST:event_txtTelefoneGreenDarkMouseExited

    private void txtSenhaGreenDarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaGreenDarkMouseEntered
        // TODO add your handling code here:
        turnOnAnimation(txtSenhaGreenDark, txtSenhaGreen);
    }//GEN-LAST:event_txtSenhaGreenDarkMouseEntered

    private void txtSenhaGreenDarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaGreenDarkMouseExited
        // TODO add your handling code here:
        turnOffAnimation(txtSenhaGreenDark, txtSenhaGreen);
    }//GEN-LAST:event_txtSenhaGreenDarkMouseExited

    private void btnCadastrarGreenDarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarGreenDarkMouseEntered
        // TODO add your handling code here:
        turnOnAnimation(btnCadastrarGreenDark, btnCadastrarGreen);
    }//GEN-LAST:event_btnCadastrarGreenDarkMouseEntered

    private void btnCadastrarGreenDarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarGreenDarkMouseExited
        // TODO add your handling code here:
        turnOffAnimation(btnCadastrarGreenDark, btnCadastrarGreen);
    }//GEN-LAST:event_btnCadastrarGreenDarkMouseExited

    private void inputSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSenhaMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_inputSenhaMouseEntered

    private void maskInputSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maskInputSenhaMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_maskInputSenhaMousePressed

    private void inputSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSenhaMouseExited


    }//GEN-LAST:event_inputSenhaMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowStateChanged

    private void verificarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verificarSenhaMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_verificarSenhaMouseEntered

    private void verificarSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verificarSenhaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_verificarSenhaMouseExited

    private void maskInputSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maskInputSenhaMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_maskInputSenhaMouseExited

    private void inputSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSenhaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_inputSenhaMouseClicked

    private void inputSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSenhaKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_inputSenhaKeyPressed

    private void inputSenhaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSenhaMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_inputSenhaMouseReleased

    private void inputSenhaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSenhaMouseMoved
        // TODO add your handling code here:


    }//GEN-LAST:event_inputSenhaMouseMoved

    private void inputSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaActionPerformed
        // TODO add your handling code here:
        String passString;
        String senha = inputSenha.getText().trim();
        passString = senha;
        validationPassword(passString);
    }//GEN-LAST:event_inputSenhaActionPerformed

    private void rodar() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCadastrarGreen;
    private javax.swing.JLabel btnCadastrarGreenDark;
    private javax.swing.JLabel caracterGreen8;
    private javax.swing.JLabel caracterRed8;
    private javax.swing.JLabel frameCadastro;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNome;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JFormattedTextField inputTelefone;
    private javax.swing.JLabel manSpace;
    private javax.swing.JLabel maskInputEmail;
    private javax.swing.JLabel maskInputNome;
    private javax.swing.JLabel maskInputSenha;
    private javax.swing.JPanel telaCadastro;
    private javax.swing.JLabel txtCriarContaGreen;
    private javax.swing.JLabel txtCriarContaGreenDark;
    private javax.swing.JLabel txtEmailGreen;
    private javax.swing.JLabel txtEmailGreenDark;
    private javax.swing.JLabel txtNomeCompletoGreen;
    private javax.swing.JLabel txtNomeCompletoGreenDark;
    private javax.swing.JLabel txtSenhaGreen;
    private javax.swing.JLabel txtSenhaGreenDark;
    private javax.swing.JLabel txtTelefone;
    private javax.swing.JLabel txtTelefoneGreen;
    private javax.swing.JLabel txtTelefoneGreenDark;
    private javax.swing.JLabel verificarSenha;
    // End of variables declaration//GEN-END:variables

    @Override
    public void turnOnAnimation(JLabel l1, JLabel l2) {
        l1.setVisible(false);
        l2.setVisible(true);
    }

    @Override
    public void turnOffAnimation(JLabel l1, JLabel l2) {
        l1.setVisible(true);
        l2.setVisible(false);
    }

    @Override
    public boolean validationPassword(String password) {
        int qtd = 0;
        String[] senhaValida = new String[8];

        for (int i = 0; i < password.length(); i++) {
            boolean validor = Character.isWhitespace(password.charAt(i));
            senhaValida[i] = String.valueOf(password.charAt(i));
            if(!validor){
                qtd++;
            }

            System.out.println(password);
        }
        System.out.println(qtd);
        
        for(int j = 0; j < senhaValida.length; j++){
            if(senhaValida[j] == null){
                qtd--;
            }
        }
        
        System.out.println(qtd);
        
        if(qtd == 8){
            caracterGreen8.setVisible(true);
        }else{
            caracterRed8.setVisible(false);
        }


        /*if (!password.isEmpty()) {
            if (password.length() < 8) {
                turnOnAnimation(caracterRed8, caracterGreen8);

            } else {
                turnOffAnimation(caracterRed8, caracterGreen8);
            }
        } else {
            caracterGreen8.setVisible(false);
            caracterRed8.setVisible(false);
        }

      /*  try {
            if (Character.isAlphabetic(password.charAt(0))) {
                JOptionPane.showMessageDialog(null, "Somente Letras");
            } else {

            }
        } catch (HeadlessException e) {
        }
        try {
            if (Character.isDigit(password.charAt(7)) == true) {
                JOptionPane.showMessageDialog(this, "Numero" + password.charAt(4));
            } else {
                JOptionPane.showMessageDialog(null, "letra");
            }
        } catch (HeadlessException e) {
        }
         */
        return true;
    }

    @Override
    public boolean validationEmail(String email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean validationName(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean validationTelephone(String telephone) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
